### ISSUE TITLE
Reason for ht-set! returning nil?

### ISSUE THREAD

**Issue by dieggsy** [Wilfred/ht.el#23]
`puthash` returns the value of the set key, just wondering if it would be better for `ht-set!`'s behavior to be consistent  with this.

**Comment by Wilfred** [comment]
It's deliberate. All the mutating functions in ht intentionally return nil.

I find it prevents accidents, so you don't end up with multiple references to the same thing. If you return the hash table the user might think the original hash table was unchanged. Returning the key or value is less confusing, but I don't think it's obvious which the user would expect to be returned.

**Comment by dieggsy** [comment]
@Wilfred I sort of follow, but could you explain what you mean by "multiple references to the same thing" in a little more detail?

**Comment by Wilfred** [comment]
If you have code that looks like this:

```emacs-lisp
(let* ((items (list 1 2 3 4))
       (odd-items (-filter #'oddp items)))
  (length items))
```

You're expecting `items` to be unmodified by `-filter`. If `-filter` modified the list and returned the modified list, this code would be broken. Instead, if `-filter` modified the original list and returned nil, you'd be less likely to be confused because you'd spot the issue sooner.
